### ISSUE TITLE
License change request (another one)

### ISSUE THREAD

**Issue by Calinou** [BKcore/HexGL#29]
Hello,

I play games that are [free/libre](http://gnu.org/philosophy/free-sw.html) software exclusively. Sadly, the CC BY-NC license is not a free software license. (By the way, the Creative Commons licenses are not software licenses.)

Would you consider making at least the code have a free license (like MIT), please? You can keep the media under CC BY-NC for now if you want.

http://freedomdefined.org/Licenses/NC

**Comment by BKcore** [comment]
Thanks for the suggestion, I'll look into it.
