### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by Krusty27** [BKcore/HexGL#49]
Hello, I **love this game**. It's too good to play without having to install anything. Continue working on it, it could become a very complex but easy to play game!

**Comment by RKDUDE02** [comment]
Well... i notice that there are people on the lead board on the games website. I play this game sometimes too!

**Comment by Nalin-Angrish** [comment]
Technically, the development of this game has been dead since years. But as the author said, he will still merge PRs that would improve the game.
